[CmdletBinding()]
param([ValidateSet('start','stop','doctor','backup','restore','update','uninstall')] [string]$Action,[string]$BackupFile,[string]$Version,[switch]$Purge,[string]$Confirm)
$ErrorActionPreference='Stop'; $Root=Split-Path -Parent $PSScriptRoot; $Compose=Join-Path $Root 'deploy\local\compose.yaml'; $EnvFile=Join-Path $Root '.env'
function Fail([string]$m){throw "AD3 Evolution: $m"}
function Require-Docker { if(!(Get-Command docker -ErrorAction SilentlyContinue)){Fail 'Docker is unavailable'}; & docker compose version | Out-Null; if($LASTEXITCODE){Fail 'Docker Compose unavailable'} }
function Run-Compose([string[]]$Args){ & docker compose --env-file $EnvFile -f $Compose @Args; if($LASTEXITCODE){Fail "compose failed: $($Args -join ' ')"} }
function Absolute([string]$Path){if(!$Path){Fail 'absolute backup path required'};$full=[IO.Path]::GetFullPath($Path);if($full -ne $Path){Fail 'backup path must be absolute'};return $full}
function Instance-Volume {
 $id=(& docker compose --env-file $EnvFile -f $Compose ps -q evolution);if(!$id){Fail 'Evolution container is not available'}
 $mounts=(& docker inspect $id | ConvertFrom-Json)[0].Mounts
 $m=$mounts|Where-Object {$_.Destination -eq '/evolution/instances'}|Select-Object -First 1
 if(!$m -or !$m.Name){Fail 'instances volume could not be resolved from container inspect'};return $m.Name
}
function Assert-ZipSafe([string]$Zip){Add-Type -AssemblyName System.IO.Compression.FileSystem;$z=[IO.Compression.ZipFile]::OpenRead($Zip);try{if($z.Entries.Count -ne 2){Fail 'backup zip must contain exactly postgres.sql and instances.tgz'};$names=@($z.Entries|ForEach-Object{$_.FullName});if(@($names|Where-Object{$_ -notin @('postgres.sql','instances.tgz')}).Count){Fail 'backup zip contains unexpected entries'};$total=[int64]0;foreach($e in $z.Entries){if($e.FullName -match '(^[\\/]|(^|[\\/])\.\.([\\/]|$))'){Fail 'zip path traversal rejected'};$total+=$e.Length;if($total -gt 20GB){Fail 'zip uncompressed size too large'}}}finally{$z.Dispose()}}
function Assert-TarSafe([string]$Tar){$names=@(& tar -tzf $Tar 2>&1);if($LASTEXITCODE -or !$names){Fail 'tar name listing is not parseable'};$details=@(& tar -tvzf $Tar 2>&1);if($LASTEXITCODE -or !$details -or $details.Count -ne $names.Count){Fail 'tar detail listing is not parseable'};if($names.Count -gt 200000){Fail 'tar has too many entries'};foreach($name in $names){if($name -match '(^/|(^|/)\.\.(/|$)|\\'){Fail 'tar path traversal rejected'}};foreach($line in $details){if($line -notmatch '^[d-]'){Fail 'tar contains non-regular entry'}}}
if(!(Test-Path $Compose)){Fail 'compose missing'}; if($Action -ne 'doctor' -and !(Test-Path $EnvFile)){Fail '.env missing'}
switch($Action){
 'doctor'{Require-Docker; if(!(Test-Path $EnvFile)){Fail '.env missing'};Run-Compose @('config','--quiet');Run-Compose @('ps')}
 'start'{Require-Docker;Run-Compose @('up','-d')}
 'stop'{Require-Docker;Run-Compose @('stop')}
 'backup'{Require-Docker;$out=Absolute $BackupFile;if(Test-Path $out){Fail 'refusing overwrite'};$tmp=Join-Path ([IO.Path]::GetTempPath()) ('ad3-'+[guid]::NewGuid());New-Item -ItemType Directory $tmp|Out-Null;try{$dump=Join-Path $tmp 'postgres.sql';& docker compose --env-file $EnvFile -f $Compose exec -T postgres pg_dump -U evolution evolution | Out-File -LiteralPath $dump -Encoding utf8;if($LASTEXITCODE){Fail 'pg_dump failed'};$v=Instance-Volume;$env:AD3_EVOLUTION_BACKUP_TEMP=$tmp;& docker run --rm -v "${v}:/data:ro" -v "${tmp}:/out" alpine tar czf /out/instances.tgz -C /data .;Remove-Item Env:AD3_EVOLUTION_BACKUP_TEMP -ErrorAction SilentlyContinue;if($LASTEXITCODE -or !(Test-Path (Join-Path $tmp 'instances.tgz'))){Fail 'volume backup failed'};Compress-Archive -Path (Join-Path $tmp '*') -DestinationPath $out -ErrorAction Stop}finally{Remove-Item Env:AD3_EVOLUTION_BACKUP_TEMP -ErrorAction SilentlyContinue;Remove-Item $tmp -Recurse -Force}}
 'restore'{Require-Docker;$zip=Absolute $BackupFile;if(!(Test-Path $zip)){Fail 'backup missing'};if($Confirm -ne 'RESTORE'){Fail 'restore requires -Confirm RESTORE'};Assert-ZipSafe $zip;$tmp=Join-Path ([IO.Path]::GetTempPath()) ('ad3-'+[guid]::NewGuid());New-Item -ItemType Directory $tmp|Out-Null;try{Expand-Archive $zip $tmp;$tar=Join-Path $tmp 'instances.tgz';$sql=Join-Path $tmp 'postgres.sql';if(!(Test-Path $tar) -or !(Test-Path $sql) -or (Get-Item $sql).Length -eq 0 -or (Get-Item $sql).Length -gt 10GB -or (Get-Item $tar).Length -eq 0 -or (Get-Item $tar).Length -gt 20GB){Fail 'invalid or unsafe backup'};Assert-TarSafe $tar;Run-Compose @('stop','evolution');Get-Content -Raw $sql|& docker compose --env-file $EnvFile -f $Compose exec -T postgres psql -v ON_ERROR_STOP=1 -U evolution evolution;if($LASTEXITCODE){Fail 'database restore failed; Evolution remains stopped'};$v=Instance-Volume;& docker run --rm -v "${v}:/data" -v "${tmp}:/in" alpine sh -c 'rm -rf /data/* /data/.[!.]*; tar xzf /in/instances.tgz -C /data';if($LASTEXITCODE){Fail 'instances restore failed; Evolution remains stopped'};Run-Compose @('up','-d')}finally{Remove-Item $tmp -Recurse -Force}}
 'update'{Require-Docker;if($Version -ne 'v2.3.7'){Fail 'only v2.3.7 is allowlisted; take a backup before update'};Run-Compose @('pull');Run-Compose @('up','-d')}
 'uninstall'{Require-Docker;if($Purge -and $Confirm -ne 'PURGE-VOLUMES'){Fail 'purge requires -Confirm PURGE-VOLUMES'};if($Purge){Run-Compose @('down','--volumes')}else{Run-Compose @('down')}}
}
